### ISSUE TITLE
Who is PHP.earth?

### ISSUE THREAD

**Issue by timofey-drozhzhin** [phpearth/PHP.earth#36]
Our company is considering the use of Docker images made by phpearth, but for security reasons we want to understand the company behind it.

I've spent over an hour researching and cannot find a single document explaining - who is PHP.earth. The Website FAQ (docs.php.earth/faq) and any other About Us resources only provide info on PHP code itself or provide links to external websites (PHP.net, Drupal, Laravel, etc...), but no info on PHPearth. 

**It would be very beneficial for the PHP.earth website to have an About Us page.**

- Is PHP.earth operated or affiliated with PHP.net?
- Is PHP.earth a non-affiliated association created by PHP.net?
- Is PHP.earth backed by any company? If so, who?
- Is PHP.earth just created by a random, very generous person(s)?
- Who directs/oversees PHP.earth?
- Is PHP.earth a Chinese government sponsored project?

May seem like comical questions, but all these are valid concerns to which we're scratching our heads and would love to see the About Us page.

**Comment by nhlm** [comment]
PHP.earth is no company and not affiliated with the PHP Group (php.net), it is a collective of people. @petk is the chief of staff and oversees all orbiting things that belongs to PHP.earth with help of @Maikuolan and me. PHP.earth is fully sponsored by private resources of the staff and has no connection to any sponsorship from any government or company.

PHP.earth is no commercial entity and does not need an about page. We had one back in the days, but the maintenance of the page and syncing all the people who are currently involved somewhere into an about page became a waste of time to us.

If there is any question regarding legal issues or the commercial usage or the usage in general of our repositories or containers, please contact @petk

**Comment by timofey-drozhzhin** [comment]
@nhlm - Thank you, this answers a lot of the questions we were having. I think having this thread on GitHub is going to be enough for anyone seeking more info.
